[pytest]
DJANGO_SETTINGS_MODULE = mycloud.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short

# Разрешить доступ к базе данных для всех тестов
django_find_project = true
