"""Фабрики для создания тестовых данных файлов

Используется библиотека factory_boy для генерации фиктивных данных.

Основные классы:
- FileFactory: создает файлы со случайным содержимым через ContentFile
"""

import uuid

import factory
from django.core.files.base import ContentFile

from users.factories import UserFactory


class FileFactory(factory.django.DjangoModelFactory):
    """Фабрика для создания файлов

    Генерирует файл со следующими полями:
    - original_name: оригинальное имя файла (на основе типа)
    - file: ContentFile с случайным содержимым
    - comment: случайный комментарий
    - user: владелец файла (через фабрику UserFactory)

    Размер файла генерируется автоматически при сохранении через save().
    special_link генерируется автоматически в методе save() модели File.
    """

    class Meta:
        model = "files.File"

    comment = factory.Faker("sentence", nb_words=4)
    user = factory.SubFactory(UserFactory)

    @factory.lazy_attribute
    def original_name(self):
        """Генерирует оригинальное имя файла

        Возвращает:
            str: Оригинальное имя файла с расширением
        """
        return f"test_file_{uuid.uuid4().hex[:8]}.txt"

    @factory.lazy_attribute
    def file(self):
        """Создает ContentFile с случайным содержимым

        Возвращает:
            ContentFile: Файл с случайным текстовым содержимым
        """
        # self.user уже является User объектом благодаря SubFactory
        content = (
            "Test file content generated by factory\n"
            f"User: {self.user.username}\n"
            f"Comment: {self.comment}\n"
            "Sample text: Test content for file upload testing."
        )
        content_bytes = content.encode("utf-8")
        return ContentFile(content_bytes, name=self.original_name)
