# Generated by Django 6.0.5 on 2026-05-25 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Оригинальное имя файла', max_length=255, verbose_name='Оригинальное имя')),
                ('file', models.FileField(help_text='Физическое расположение файла на сервере', upload_to=files.models.upload_to, verbose_name='Файл')),
                ('comment', models.TextField(blank=True, help_text='Описание или заметка к файлу', verbose_name='Комментарий')),
                ('size', models.BigIntegerField(default=0, help_text='Размер файла в байтах', verbose_name='Размер файла (байт)')),
                ('upload_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время загрузки', verbose_name='Дата загрузки')),
                ('special_link', models.CharField(blank=True, help_text='Уникальная ссылка для скачивания файла', max_length=32, unique=True, verbose_name='Специальная ссылка')),
                ('user', models.ForeignKey(help_text='Владелец файла', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-upload_at'],
            },
        ),
    ]
