# Generated by Django 6.0.5 on 2026-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_download_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего скачивания файла', null=True, verbose_name='Дата последнего скачивания'),
        ),
    ]
