# Generated by Django 6.0.5 on 2026-06-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_last_download_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_name',
            field=models.CharField(blank=True, default='', help_text='Оригинальное имя файла', max_length=255, verbose_name='Оригинальное имя'),
        ),
    ]
