# Generated by Django 6.0.5 on 2026-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_alter_file_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="original_name",
            field=models.CharField(
                help_text="Оригинальное имя файла",
                max_length=255,
                verbose_name="Оригинальное имя",
            ),
        ),
    ]
